Bump to the latest Guava version to avoid CVEs and be up to date
OWASP/java-html-sanitizer pull request #295
Opened 2023-12-13 04:05 UTC by casewalker

Upgrades past CVE-2023-2976 and CVE-2020-8908 to the latest Guava version.

2023-12-13 04:06 UTC, casewalker commented
@mikesamuel If you could take a look, that would be greatly appreciated.

2023-12-18 18:02 UTC, melloware commented
+1

2023-12-19 20:33 UTC, maxibarros commented
+1 @mikesamuel

2023-12-19 20:35 UTC, melloware requested changes

2023-12-19 20:35 UTC, melloware commented on parent/pom.xml
> +    <guava.version>32.1.3-jre</guava.version>
33.0.0-jre

2023-12-20 15:49 UTC, subbudvk commented
I think dependabot can create such PR. Saw one for another version - https://github.com/OWASP/java-html-sanitizer/pull/284. Also there is some discussion on removing the dependency https://github.com/OWASP/java-html-sanitizer/pull/272

2023-12-20 23:45 UTC, casewalker commented
@subbudvk If you read the comments on the PR you linked and check the Guava link I shared above, you'll see that the Dependabot PR is trying to upgrade from one vulnerable version to another vulnerable version.

2024-01-12 13:21 UTC, casewalker commented
@jmanico Hello, I saw that you recently reviewed a PR in this repo. I am trying to have some CVEs addressed by bumping to the latest version of Guava. If you could review this PR, that would be greatly appreciated.

Thanks!

2024-01-15 16:40 UTC, melloware commented
@casewalker this can be closed now that https://github.com/OWASP/java-html-sanitizer/pull/272 has been merged

2024-01-15 16:40 UTC, mikesamuel commented
This is obviated by https://github.com/OWASP/java-html-sanitizer/commit/3b6cc1b7e6d7992c5b15f87f91dc163de7d35c05 which removes the guava dependency entirely

2024-01-15 16:40 UTC, closed without merging

2024-01-15 19:37 UTC, casewalker commented
Beautiful, thanks for addressing the underlying issue!!